python -m tests.alphabetmodel
python -m tests.chordcategorization
python -m tests.dictreaderutils
python -m tests.fileutils
python -m tests.inputinterpreter
python -m tests.keyhighlighting
python -m tests.lessondirective
python -m tests.lessonfiller
python -m tests.lessonfinder
python -m tests.lessonmapper
python -m tests.tintkeys
python -m tests.wordchooserinc
python -m tests.wordchooserinorder
python -m tests.wordmodel
python -m tests.wordstochords
