# Copyright (c) 2011 Pragma Nolint. 
# See LICENSE.txt for details.

"""High contrast black, white and yellow, helpful for low vision users."""

WHITE = (255, 255, 255)
BLACK = (0,0,0)

CANVAS_COLOR = WHITE

MENU_BAR_COLOR = BLACK
MENU_BAR_TEXT_COLOR = WHITE
WORD_TEXT_COLOR = WHITE
WORD_BACKGROUND_COLOR = BLACK

TEXT_INPUT_BACKGROUND_COLOR = BLACK
TEXT_INPUT_TEXT_COLOR = WHITE
CAPTION_TEXT_COLOR = BLACK 
CAPTION_BACKGROUND_COLOR = CANVAS_COLOR

SPEED_BAR_BACKGROUND_COLOR = WORD_BACKGROUND_COLOR 
SPEED_BAR_TEXT_COLOR = WHITE

OPTION_BACKGROUND_COLOR = WHITE
OPTION_TEXT_COLOR = BLACK
BUTTON_HOVER_INCREMENT = (0, 0, -255)
BUTTON_PRESSED_INCREMENT = (-255, -255, -255)

INFO_PANEL_BACKGROUND_COLOR = OPTION_BACKGROUND_COLOR
INFO_PANEL_TEXT_COLOR = (0, 0, 0)
INFO_PANEL_CAPTION_TEXT_COLOR = (0, 0, 0)

QWERTY_KEY_BACKGROUND_COLOR = BLACK
QWERTY_KEY_TEXT_COLOR = WHITE
STENO_KEY_TEXT_COLOR = WHITE
KEY_LIT_INCREMENT = (255, 255, 0)
PARTIAL_LIT_INCREMENT = (200, 200, 0)
HIGHLIGHTED_KEY_TEXT_COLOR = BLACK

STINT_QWERTY_KEY_BACKGROUND_COLOR = (45, 40, 40)
STINT_QWERTY_KEY_TEXT_COLOR = (0, 0, 50) 
STINT_STENO_KEY_TEXT_COLOR = (155, 150, 150)
V_KEY_STENO_COLOR = (115, 115, 115)

